apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-k8s-demo
  labels:
    app: java-k8s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-k8s-demo
  template:
    metadata:
      labels:
        app: java-k8s-demo
    spec:
      imagePullSecrets:
        - name: dockerhub-cred
      containers:
        - name: app
          image: chand93/java-k8s-demo:dev   # or :v1 if you pushed it
          imagePullPolicy: IfNotPresent         # avoids unnecessary pulls
          ports:
            - containerPort: 8088
          readinessProbe:
            httpGet:
              path: /health
              port: 8088
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8088
            initialDelaySeconds: 10
            periodSeconds: 20

