apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-k8s-demo
  labels:
    app: java-k8s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-k8s-demo
  template:
    metadata:
      labels:
        app: java-k8s-demo
    spec:
      containers:
        - name: app
          image: chandan1693/java-k8s-demo:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
